project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "Notebook_*.py"

website:
  title: "FlyVis-GNN"
  navbar:
    tools:
      - icon: github
        href: https://github.com/saalfeldlab/flyvis-gnn
  page-footer: "Copyright 2026, Saalfeld Lab"
  repo-url: https://github.com/saalfeldlab/flyvis-gnn/
  site-url: https://saalfeldlab.github.io/flyvis-gnn/
execute:
  enabled: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: show
    code-overflow: wrap
    code-tools:
      source: repo
