description: "Optimized config from 144-iteration Claude exploration (winner: Config 03, Node 144)"
dataset: flyvis_62_1_gs
simulation:
  connectivity_file: to be specified
  adjacency_matrix: ""
  params:
    - - 1.0
      - 1.0
      - 1.0
      - 1.0
  n_neurons: 13741
  n_input_neurons: 1736
  n_neuron_types: 65
  n_edges: 434112
  n_frames: 64000
  delta_t: 0.02
  baseline_value: 0
  visual_input_type: DAVIS
  noise_model_level: 0.05
graph_model:
  signal_model_name: flyvis_A
  prediction: first_derivative
  input_size: 3
  n_layers: 3
  hidden_dim: 80
  output_size: 1
  input_size_update: 5
  n_layers_update: 3
  hidden_dim_update: 80
  aggr_type: add
  embedding_dim: 2
  update_type: generic
  lin_edge_positive: true
plotting:
  colormap: tab20
  arrow_length: 1
  xlim:
    - -2.5
    - 2.5
  ylim:
    - -100
    - 100
training:
  n_epochs: 5
  n_runs: 1
  device: auto
  recurrent_training: false
  batch_size: 2
  batch_ratio: 1
  small_init_batch_size: false
  sparsity: none
  data_augmentation_loop: 20
  learning_rate_W_start: 0.0006
  learning_rate_start: 0.0012
  learning_rate_embedding_start: 0.00155
  coeff_edge_diff: 750
  coeff_update_u_diff: 0
  coeff_update_msg_diff: 0
  coeff_edge_norm: 0.9
  coeff_edge_weight_L1: 0.28
  coeff_phi_weight_L1: 0.5
  coeff_phi_weight_L1_rate: 0.5
  coeff_edge_weight_L2: 0
  coeff_phi_weight_L2: 0.001
  coeff_W_L1: 5.0e-05
  coeff_W_L1_rate: 0.5
  coeff_W_L2: 3.0e-06
  w_init_mode: zeros
