description: 'no extra null edges, noise_model_level: 0  coeff_g_phi_diff: 0 coeff_g_phi_norm:
  0  training seed: 24   benchmark LSTM  training on 10 neurons 64000 frames'
dataset: flyvis_62_1
simulation:
  connectivity_file: to be specified
  adjacency_matrix: ''
  params:
  - - 1.0
    - 1.0
    - 1.0
    - 1.0
  n_neurons: 10
  n_input_neurons: 10
  n_neuron_types: 65
  n_edges: 434112
  n_frames: 64000
  delta_t: 0.02
  baseline_value: 0
  visual_input_type: DAVIS
  noise_model_level: 0
  seed: 42
graph_model:
  signal_model_name: flyvis_LSTM
  prediction: first_derivative
  input_size: 20
  output_size: 10
  hidden_dim: 256
  n_layers: 3
  MLP_activation: relu
  aggr_type: add
  embedding_dim: 2
  update_type: generic
  g_phi_positive: true
plotting:
  colormap: tab20
  arrow_length: 1
  xlim:
  - -2.5
  - 5
  ylim:
  - -100
  - 100
training:
  n_epochs: 10
  n_runs: 1
  device: auto
  seed: 241
  training_selected_neurons: true
  selected_neuron_ids:
  - 10703
  - 9618
  - 8967
  - 8099
  - 7231
  - 6363
  - 0
  - 4193
  - 3976
  - 1736
  batch_size: 1
  batch_ratio: 1
  sparsity: none
  data_augmentation_loop: 25
  learning_rate_W_start: 0.001
  learning_rate_start: 0.0005
  learning_rate_embedding_start: 0.005
  measurement_noise_level: 0
  coeff_g_phi_diff: 0
  coeff_f_theta_msg_diff: 0
  coeff_g_phi_norm: 0
  w_init_mode: zeros
