description: 'small MLP, no extra null edges,  hidden_dim_nnr: 64'
dataset: 'flyvis_18_4_0'

simulation:
    connectivity_file: 'to be specified'
    adjacency_matrix: ''

    params: [[1.0,1.0,1.0,1.0]]

    n_neurons: 13741
    n_input_neurons: 1736
    n_neuron_types: 20
    n_edges: 434112
    n_frames: 20000
    delta_t: 0.02
    baseline_value: 0
    noise_model_level: 5.0E-1


graph_model:
    signal_model_name: 'flyvis_A'
    prediction: 'first_derivative'
    field_type: 'visual'

    input_size: 3
    output_size: 1
    hidden_dim: 32
    n_layers: 2

    input_size_update: 5
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 64
    output_size_nnr: 1736
    outermost_linear_nnr: True
    omega: 30

    update_type: 'generic'
    g_phi_positive: True


plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [ -2.5,2.5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 10
    n_runs: 1
    device: 'auto'

    batch_size: 1
    batch_ratio: 1

    sparsity: 'none'
    data_augmentation_loop: 100

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3
    learning_rate_NNR: 1.0E-5

    measurement_noise_level: 0
    coeff_g_phi_diff: 500
    coeff_f_theta_msg_diff: 0
    coeff_g_phi_norm: 1.0